version: '3.7'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
      start_period: 5s
  postgres-data:
      image: postgres:13
      environment:
        POSTGRES_USER: datauser
        POSTGRES_PASSWORD: datapass
        POSTGRES_DB: realmadrid_db
      ports:
        - "5437:5432"
      volumes:
        - pgdata_silver:/var/lib/postgresql/data
        - ./postgres-init:/docker-entrypoint-initdb.d

  airflow-webserver:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "mi_clave_super_secreta_123"
      AIRFLOW_CONN_FS_DEFAULT: 'fs_default@/?path=%2F'
      AIRFLOW_CONN_POSTGRES_REALMADRID: 'postgresql://datauser:datapass@postgres-data:5432/realmadrid_db'
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - C:/Users/Esteban/Documents/Data_analysis/Project/datalake_bronze:/opt/airflow/datalake_bronze
      - C:/Users/Esteban/Documents/Data_analysis/Project/datalake_silver:/opt/airflow/datalake_silver
      - C:/Users/Esteban/Documents/Data_analysis/Project/datalake_gold:/opt/airflow/datalake_gold
      - ./dashboard:/opt/dashboard
    entrypoint: >
      bash -c "airflow db upgrade &&
      airflow users create --username admin --firstname Air --lastname Flow --role Admin --email admin@example.com --password admin || true &&
      rm -f /opt/airflow/airflow-webserver.pid &&
      airflow webserver"

  airflow-scheduler:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "mi_clave_super_secreta_123"
      AIRFLOW_CONN_FS_DEFAULT: 'fs_default@/?path=%2F'
      AIRFLOW_CONN_POSTGRES_REALMADRID: 'postgresql://datauser:datapass@postgres-data:5432/realmadrid_db'
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - C:/Users/Esteban/Documents/Data_analysis/Project/datalake_bronze:/opt/airflow/datalake_bronze
      - C:/Users/Esteban/Documents/Data_analysis/Project/datalake_silver:/opt/airflow/datalake_silver
      - C:/Users/Esteban/Documents/Data_analysis/Project/datalake_gold:/opt/airflow/datalake_gold
      - ./dashboard:/opt/dashboard
    entrypoint: >
      bash -c "airflow db upgrade &&
      airflow scheduler"
  dashboard:
    build: .
    depends_on:
      - airflow-scheduler
    ports:
      - "8051:8051"
    volumes:
      - ./dashboard:/opt/dashboard
      - C:/Users/Esteban/Documents/Data_analysis/Project/datalake_gold:/opt/airflow/datalake_gold
    command: python /opt/dashboard/storytelling_app.py
volumes:
  pgdata:
  pgdata_silver: 
